Cargo.lock, README.md, canbench-bin/Cargo.toml, canbench-bin/src/lib.rs, canbench-bin/src/print_benchmark.rs, canbench-bin/src/results_file.rs, canbench-rs-macros/Cargo.toml, canbench-rs-macros/src/lib.rs, canbench-rs/Cargo.toml, canbench-rs/src/lib.rs, examples/Cargo.toml, examples/btreemap_vs_hashmap/canbench.yml, examples/btreemap_vs_hashmap/src/main.rs, examples/fibonacci/canbench.yml, examples/fibonacci/src/main.rs, tests/Cargo.toml, tests/gzipped_wasm/src/main.rs, tests/measurements_output/src/main.rs
Due to naming conflicts on crates.io, we cannot publish both the canbench
Rust library and the canbench binary with the same name.
We therefore rename the Rust library to canbench-rs.
=> chore: rename canbench rust library to canbench-rs

scripts/ci_run_benchmark.sh
The script failed to detect a special case of performance regression - specifically, when the regression is from zero.
The current way we check for regressions is quite brittle and is best to be addressed with error code in the future.
=> fix: detect regressions from zero in the CI script

.github/workflows/canbench-post-comment.yml, scripts/ci_download_canbench_artifacts.sh
Due to the way Github Actions are setup for security reasons, canbench comments weren't working for PRs from forked repositories.
Rather than commenting directly from CI, we now add a separate workflow that will be triggered once CI is complete, and that workflow will post the comment.
In a followup PR, the CI itself will be updated to use the workflow we're adding here. It cannot be added in the same PR.
=> fix: canbench post comment in CI from forked repos (part 1)

.github/workflows/ci.yml, scripts/ci_run_benchmark.sh
This PR builds on #43 to update the CI such that canbench can post comments from forked PRs.
=> fix: posting comments from forked repos

Cargo.lock, Cargo.toml
When using the default features of reqwest, it pulls in `native-tls` which depends on `openssl`. Therefore, when such dependency exists in the IC monorepo, it will fail the [binary-libraries-test.sh](https://sourcegraph.com/github.com/dfinity/ic@4d851cbcf6b0379ae83411997e18358fbdba6e71/-/blob/publish/binaries/binary-libraries-test.sh).
When setting the default-features to false without adding `rustls-tls-native-roots`, the tests fail because `drun` cannot be downloaded with`https://`. Either `rustls-tls-native-roots` or `rustls-tls-webpki-roots`seems to work and it doesn't seem to make much difference here. Choosing `rustls-tls-webpki-roots` as it's the same as the [monorepo](https://sourcegraph.com/github.com/dfinity/ic@4d851cbcf6b0379ae83411997e18358fbdba6e71/-/blob/bazel/external_crates …
=> chore: Use RustLs instead of OpenSSL for reqwest

Cargo.lock, canbench-bin/Cargo.toml, canbench-bin/tests/tests.rs
Updates the version of canbench to release it with the change in #47.
=> chore: update version of canbench

Cargo.lock, canbench-bin/Cargo.toml, canbench-bin/tests/tests.rs
Some notable changes have been introduced that are worthy of a new release:
1. Support for init args.
2. Switching the runtime from `drun` to `PocketIC`
=> chore: bump version to 0.1.4

.github/workflows/conventional-commits.yml
We need to sanitize the PR title by leveraging an environment variable as an intermediate step to prevent potential script injection attacks. This additional measure enhances the security of the workflow.
=> fix(ci): Sanitize PR title by using ENV variable

canbench-bin/src/lib.rs, canbench-bin/tests/tests.rs, tests/measurements_output/src/main.rs
canbench was formerly using a system subnet to benchmark instructions. As noted in #61, there are differences between how instructions are accounted in system subnets vs application subnets, where the application subnets are more accurate, especially when it comes to accounting for stable memory writes.
Use an application subnet configuration rather than a system subnet to more correctly account instructions.
Closes #61
=> fix: correctly account for instructions when writing stable memory

examples/btreemap_vs_hashmap/canbench_results.yml, scripts/ci_run_benchmark.sh
The CI is downloading a version of canbench from crates.io, which means the benchmarks do not capture any performance changes from the current PR.
Update the CI script to build canbench from HEAD.
Note the regression in the btreemap example due to the change in pricing of stable memory operations in later versions of canbench.
=> fix: use canbench from HEAD in CI

canbench-bin/src/lib.rs, canbench-bin/src/main.rs, canbench-bin/tests/tests.rs, canbench-bin/tests/utils.rs
To enable running canbench without flakiness in the `ic` repo, it is desirable to able to specify a path for the runtime (pocket ic) to use. canbench didn't provide that flexibility, as it always downloads the runtime from the network.
Add two flags, one to set the path to the runtime, and another to skip the hash verification step altogether.
=> feat: add flags to specify a custom runtime.

canbench-bin/src/lib.rs
This allows for the output from the pocket-ic server to be exposed, which can help in debugging benchmark setups.
=> feat: expose POCKET_IC_MUTE_SERVER env variable

canbench-bin/src/lib.rs, canbench-bin/src/main.rs, canbench-bin/src/print_benchmark.rs, canbench-bin/tests/tests.rs, canbench-bin/tests/utils.rs, tests/measurements_output/canbench_results.yml, tests/measurements_output/src/main.rs
For some projects, there are some small variances in the performance, and from time to time people have to update the results for small changes. For projects with more frequent commits, the chances of having conflicts is greater, and the convenience of avoiding such conflicts sometimes outweighs the benefits of detecting small performance changes.
- Add `--custom-noise-threshold` CLI option
- Use the custom threshold if it exists
- Add tests
One alternative is to add the argument to `Config` instead. There doesn't seem to be a clear pros/cons for whether to add to CLI or Config. For IC monorepo, it's easier to use CLI option because of bazel.
=> feat: Support custom noise threshold

.github/workflows/ci.yml, Cargo.lock, canbench-bin/tests/tests.rs, canbench-rs/src/lib.rs, examples/btreemap_vs_hashmap/canbench_results.yml, examples/fibonacci/canbench_results.yml, rust-toolchain.toml, tests/init_arg/canbench_results.yml, tests/init_arg/src/main.rs
The upgrade is required by the https://github.com/dfinity/stable-structures/pull/267
=> ci: Upgrade Rust toolchain to 1.84

canbench-bin/src/csv_file.rs, canbench-bin/src/lib.rs, canbench-bin/src/main.rs, canbench-rs/src/lib.rs, examples/btreemap_vs_hashmap/canbench_results.csv, examples/btreemap_vs_hashmap/canbench_results.yml, examples/fibonacci/canbench_results.csv, examples/fibonacci/canbench_results.yml
Add CSV export with `--persist` flag for easier benchmark analysis.
This PR enables writing benchmark results to a CSV file when the `--persist` flag is used.
It helps improve readability and analysis of large benchmark sets by allowing results to be inspected in spreadsheet software.
=> feat: add CSV reporting support

canbench-bin/src/lib.rs, canbench-bin/src/main.rs
Decouple CSV reporting from `--persist` and introduce `--csv` flag.
This change ensures that `--persist` behaves as before, updating only `canbench_results.yml` without generating additional files. CSV reporting is now controlled separately via the new `--csv` flag, allowing clearer intent and cleaner output management.
=> feat: control CSV reporting via --csv flag

canbench-bin/src/summary.rs, canbench-bin/tests/tests.rs
This PR replaces the generic `changed` count with separate `improved` and `regressed` counters for better clarity.
It also unifies the formatting of all summary lines to match the style of `change` and `change %`, and adds emoji indicators to highlight important changes at a glance.
The summary output format is inspired by the style used in the [Criterion](https://bheisler.github.io/criterion.rs/book/user_guide/command_line_output.html) crate.
=> feat: improve summary output with separate counters and clearer formatting

canbench-bin/src/csv_file.rs, examples/btreemap_vs_hashmap/canbench_results.csv, examples/fibonacci/canbench_results.csv
This PR changes the CSV delimiter to a comma (,) for better compatibility with GitHub and VSCode CSV previews.
This allows to easily sort tables right in your VSCode editor.
=> feat: switch CSV delimiter from tab to comma

.github/workflows/ci.yml, .github/workflows/conventional-commits.yml, scripts/ci_run_benchmark.sh
This PR enhances the CI benchmark reporting by showing a summary message.
It also improves the canbench report header by including commit metadata and performance summary markers.
It was previously tested in [bitcoin-canister repo](https://github.com/dfinity/bitcoin-canister/pull/372#issuecomment-2687361621).
- Adjusts canbench command flags to display a summary
- Updates the CI script to include the latest commit hash and timestamp in the canbench report message and append summary markers for performance changes, [example](https://github.com/dfinity/canbench/pull/105#issuecomment-2862249363)
- Updates the CI workflow to enforce colored output and adjusts job dependency formatting
=> ci: show summary in canbench report message

Cargo.lock, canbench-bin/Cargo.toml, canbench-bin/tests/tests.rs, canbench-rs-macros/Cargo.toml, canbench-rs/Cargo.toml
This PR bumps the version numbers from 0.1.11 to 0.1.12 across the project to ensure consistency between the main library, macros, and binary packages.
- Update version in `canbench-rs/Cargo.toml` and corresponding dependency comment.
- Update version in `canbench-rs-macros/Cargo.toml`.
- Update version string in tests and `canbench-bin/Cargo.toml`.
=> chore: bump versions to 0.1.12

Cargo.lock, Cargo.toml, canbench-rs/src/lib.rs, examples/btreemap_vs_hashmap/src/main.rs, tests/stable_memory/src/main.rs
This PR downgrades ic-cdk to v0.17.2 since v0.18.0 has been yanked.
=> fix: downgrade ic-cdk to 0.17.2

Cargo.lock, canbench-bin/Cargo.toml, canbench-bin/tests/tests.rs, canbench-rs-macros/Cargo.toml, canbench-rs/Cargo.toml
This PR bumps the version numbers from 0.1.12 to 0.1.13 across the project to ensure consistency between the main library, macros, and binary packages.
- Update version in `canbench-rs/Cargo.toml` and corresponding dependency comment.
- Update version in `canbench-rs-macros/Cargo.toml`.
- Update version string in tests and `canbench-bin/Cargo.toml`.
=> chore: bump versions to v0.1.13

canbench-bin/src/csv_file.rs, canbench-bin/src/data.rs, canbench-bin/src/fmt.rs, canbench-bin/src/summary.rs, canbench-bin/src/table.rs, examples/btreemap_vs_hashmap/canbench_results.csv, examples/fibonacci/canbench_results.csv
This PR adds absolute delta columns for each metric to the CSV report.
The summary remains concise for a quick overview, while the CSV report now includes detailed information: current value, absolute change, and relative change for each metric.
=> feat: add absolute delta columns for each metric to CSV report

canbench-bin/src/data.rs, canbench-bin/src/lib.rs, canbench-bin/src/table.rs
This PR improves summary readability by adding `max_displayed_rows` limit to the summary table.
Example:
```
---------------------------------------------------
Only significant changes:
| status | name             |   ins |  ins Δ% | HI |  HI Δ% | SMI |  SMI Δ% |
|--------|------------------|-------|---------|----|--------|-----|---------|
|        | bench_1          | 9.00M | -10.00% |  0 |        |   0 |         |
|  ...   | (3 rows omitted) |       |         |    |        |     |         |
|        | bench_5          | 9.00M | -10.00% |  0 |        |   0 |         |
---------------------------------------------------
```
=> feat: add max displayed rows limit to the summary table

canbench-bin/src/summary.rs, canbench-bin/tests/expected/benchmark_reports_improvement.txt, canbench-bin/tests/expected/benchmark_reports_no_changes.txt, canbench-bin/tests/expected/benchmark_reports_no_changes_with_hide_results.txt, canbench-bin/tests/expected/benchmark_reports_noisy_change.txt, canbench-bin/tests/expected/benchmark_reports_noisy_change_above_default_noise_threshold.txt, canbench-bin/tests/expected/benchmark_reports_noisy_change_within_custom_noise_threshold.txt, canbench-bin/tests/expected/benchmark_reports_regression.txt, canbench-bin/tests/expected/benchmark_reports_regression_from_zero.txt, canbench-bin/tests/expected/benchmark_works_with_init_args.txt, canbench-bin/tests/expected/reports_repeated_scope_in_existing_benchmark.txt, canbench-bin/tests/expected/reports_scopes_in_existing_benchmark.txt
This PR updates the summary output format from `min | med | max` to `max | p75 | median | p25 | min`.
The new layout gives a clearer picture of value distribution, as the interquartile range (`p75`–`p25`) is typically more representative than extreme `max`/`min` values, which may be outliers.
=> feat: switch summary stats to five-number format

.github/workflows/ci.yml, scripts/ci_run_benchmark.sh
This PR fixes benchmark run script to upload CSV report when no main reference is available.
It also simplifies CI yaml configuration to support matrix strategy for better multi-benchmarks support.
=> ci: fix benchmark run script

Cargo.lock, canbench-rs/src/lib.rs, examples/btreemap_vs_hashmap/canbench.yml, examples/fibonacci/canbench.yml, tests/debug_print/canbench.yml, tests/gzipped_wasm/build.sh, tests/init_arg/canbench.yml, tests/measurements_output/canbench.yml, tests/newer_version/canbench.yml, tests/stable_memory/canbench.yml, tests/stable_memory_invalid/canbench.yml
This PR uses `--locked` flag for building benchmarks to avoid 3rd party dependency noise.
=> fix: use cargo build locked to remove noise from measurements

canbench-bin/tests/expected/benchmark_reports_noisy_change_above_default_noise_threshold.txt, canbench-bin/tests/expected/benchmark_reports_noisy_change_within_custom_noise_threshold.txt, canbench-bin/tests/expected/reports_nested_scopes_benchmark.txt, canbench-bin/tests/expected/reports_recursive_scopes_benchmark.txt, canbench-bin/tests/expected/reports_repeated_scope_in_existing_benchmark.txt, canbench-bin/tests/expected/reports_repeated_scope_in_new_benchmark.txt, canbench-bin/tests/expected/reports_scopes_in_existing_benchmark.txt, canbench-bin/tests/expected/reports_scopes_in_new_benchmark.txt, canbench-bin/tests/tests.rs, canbench-rs/src/lib.rs, tests/measurements_output/canbench_results.yml, tests/measurements_output/src/main.rs
Fixes overcounting of instructions in recursive scopes
Previously, instruction counts were summed for each scope without accounting for overlaps, leading to inflated scope totals in recursive calls. This change ensures instruction usage is calculated accurately by avoiding double-counting.
=> fix: fix recursive scope overcounting

Cargo.toml, canbench-bin/Cargo.toml
Running `cargo install canbench` produces a `canbench` binary running into the following error:
```
Downloading runtime (will be cached for future uses)...
Failed to validate PocketIC server binary: `Incompatible PocketIC server version: got pocket-ic-server 9.0.1; expected pocket-ic-server 9.0.2.`. Going to download PocketIC server 9.0.2 from https://github.com/dfinity/pocketic/releases/download/9.0.2/pocket-ic-x86_64-linux.gz to the local path /tmp/pocket-ic-server-9.0.2/pocket-ic. To avoid downloads during test execution, please specify the path to the (ungzipped and executable) PocketIC server 9.0.2 using the function `PocketIcBuilder::with_server_binary` or using the `POCKET_IC_BIN` environment variable.
```
This is because `canbench` specifies `pocket-ic = "9.0.0"` and there is a …
=> fix: pin pocket-ic to an exact version

.gitignore, canbench-bin/src/summary.rs, canbench-bin/tests/expected/benchmark_heap_increase.txt, canbench-bin/tests/expected/benchmark_instruction_tracing.txt, canbench-bin/tests/expected/benchmark_reports_improvement.txt, canbench-bin/tests/expected/benchmark_reports_no_changes.txt, canbench-bin/tests/expected/benchmark_reports_no_changes_with_hide_results.txt, canbench-bin/tests/expected/benchmark_reports_noisy_change.txt, canbench-bin/tests/expected/benchmark_reports_noisy_change_above_default_noise_threshold.txt, canbench-bin/tests/expected/benchmark_reports_noisy_change_within_custom_noise_threshold.txt, canbench-bin/tests/expected/benchmark_reports_regression.txt, canbench-bin/tests/expected/benchmark_reports_regression_from_zero.txt, canbench-bin/tests/expected/benchmark_stable_memory_increase.txt, canbench-bin/tests/expected/benchmark_stable_writes.txt, canbench-bin/tests/expected/benchmark_works_with_init_args.txt, canbench-bin/tests/expected/reports_recursive_scopes_benchmark.txt, canbench-bin/tests/expected/reports_repeated_scope_in_existing_benchmark.txt, canbench-bin/tests/expected/reports_repeated_scope_in_new_benchmark.txt, canbench-bin/tests/expected/reports_scopes_in_existing_benchmark.txt, canbench-bin/tests/expected/reports_scopes_in_new_benchmark.txt, canbench-bin/tests/expected/supports_gzipped_wasm.txt, examples/fibonacci/canbench_results.yml, scripts/ci_run_benchmark.sh
This PR refines benchmark summary statuses and fixes canbench results up-to-date check.
Changes:
- the summary reflects newly added benchmarks
- up-to-date script can detect changes not only from streaming results, but also from summary status
=> ci: fix up-to-date benchmark results check

.github/workflows/ci.yml, scripts/ci_run_benchmark.sh
This PR uploads persisted `canbench_results.yml` files as CI artifacts.
=> ci: upload persisted canbench_results.yml file
